### ISSUE TITLE
Events Page

### ISSUE THREAD

**Issue by manangoel99** [OSDG-IIITH/OSDG-IIITH.github.io#7]
Create a page containing a timeline of OSDG's past and upcoming events. Inspiration for the timeline can be taken from https://jekyll-themes.com/timeline/ .

**Comment by umangS77** [comment]
Do we need events as a post or a list in timeline? I mean should I add events in timeline directly in html file as a list or we need a folder for events posts and then show them on timeline?

**Comment by manangoel99** [comment]
Assigned to @umangS77
